export const paths = {
    home: "/",
    unauthorized: "/401",
    forbidden: "/403",
    serverError: "/500",
    adoptie: "/adoptie",
    pierdute: "/pierdute",
    veterinari: "/veterinari",
    donatii: "/donatii",
    sitters: "/sitters",
    voluntariat: "/voluntariat",
    evenimente: "/evenimente",
    vanzari: "/vanzari",
    cos: "/cos",
    quiz: "/quiz",
    login: "/login",
    signup: "/signup",
    profile: "/profile",
    wallet: "/portmoneu",
    legacyWallet: "/portofel",
    adminStatistici: "/admin/statistici",
    adminPagini: "/admin/pagini",
    adminUtilizatori: "/admin/utilizatori",
    adminVoluntariat: "/admin/voluntariat",
    adminRetrageri: "/admin/retrageri",
    notfound: "*",
} as const;
