export const paths = {
    home: "/",
    adoptie: "/adoptie",
    pierdute: "/pierdute",
    veterinari: "/veterinari",
    donatii: "/donatii",
    sitters: "/sitters",
    voluntariat: "/voluntariat",
    wiki: "/wiki",
    ghidMedical: "/ghid-medical",
    quiz: "/quiz",
    login: "/login",
    signup: "/signup",
    notfound: "*",
} as const;
